language: go

go: 
 - 1.x

install:
 - go mod tidy -v && go mod download

script:
 - go test -race $(go list ./... | grep -v /vendor/)

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/artemnikitin/crawler"
